### ISSUE TITLE
Update ideas

### ISSUE THREAD

**Issue by sNok3** [Sples1/ENT_Tomori#1]
For the upcoming updates I've gathered some ideas:
1. Add a whitelist for allowed IPs and Websites for the filter.
2. Add a !tag command to allow users to disable their tag.
3. Allow each owner to use different colors in all types of messages.
4. Add a block for sm_plugins so no one can see them.

**Comment by Sples1** [comment]
3) Default color has been removed from the ChatPrefix

**Comment by Sples1** [comment]
1) Added as a ConVar

**Comment by Sples1** [comment]
2. Added command !tag with custom flag settings

**Comment by Sples1** [comment]
4. Bara made a cool plugin for that <3
